Feat: vesting contract
swr1bm86/code-claim-site pull request #1
Opened 2022-04-25 21:19 UTC by zjhmale

Fixes https://github.com/Developer-DAO/code-claim-site/issues/84

2022-04-26 11:47 UTC, zjhmale commented
```
-------------------------|----------|----------|----------|----------|----------------|
File                     |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------|----------|----------|----------|----------|----------------|
 src/                    |      100 |    79.41 |      100 |      100 |                |
  CODE.sol               |      100 |      100 |      100 |      100 |                |
  ClaimCODE.sol          |      100 |    91.67 |      100 |      100 |                |
  MerkleProof.sol        |      100 |      100 |      100 |      100 |                |
  Vesting.sol            |      100 |       70 |      100 |      100 |                |
 src/deprecated/         |        0 |        0 |        0 |        0 |                |
  CODEToken.sol          |        0 |        0 |        0 |        0 |... 62,66,70,71 |
 src/mocks/              |      100 |      100 |      100 |      100 |                |
  MerkleProofWrapper.sol |      100 |      100 |      100 |      100 |                |
-------------------------|----------|----------|----------|----------|----------------|
All files                |    74.71 |     58.7 |    73.08 |    74.71 |                |
-------------------------|----------|----------|----------|----------|----------------|
```

2022-04-27 08:30 UTC, parseb requested changes

2022-04-27 08:30 UTC, parseb commented on packages/hardhat/src/Vesting.sol
> +    function addPayees(address[] memory _payees, uint256[] memory _shares) public {
onlyOwner maybe? what am I missing?

2022-04-27 08:30 UTC, parseb commented on packages/hardhat/src/Vesting.sol
> +        address account = _msgSender();
I would use msg.sender

2022-05-05 21:36 UTC, zjhmale commented on packages/hardhat/src/Vesting.sol
> +        address account = _msgSender();
for reducing gas cost maybe?

2022-05-05 21:37 UTC, zjhmale commented on packages/hardhat/src/Vesting.sol
> +    function addPayees(address[] memory _payees, uint256[] memory _shares) public {
correct, will fix that!

2022-05-05 21:40 UTC, closed without merging